# Generated by Django 5.2.2 on 2025-06-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address_order_city_order_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_unlocked',
        ),
    ]
