# Generated by Django 5.2.2 on 2025-06-09 10:01

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[accounts.validators.phone_number_validator]),
        ),
    ]
