# Generated by Django 5.2.2 on 2025-06-09 10:03

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_addresses_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='phone_number',
            field=models.CharField(default=9072731428, max_length=15, validators=[accounts.validators.phone_number_validator]),
            preserve_default=False,
        ),
    ]
